baseURL = 'https://funon.xyz/'
languageCode = 'en-us'
title = 'Funon'
theme = 'hugo-theme-funon'


[menu]

[[menu.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
[[menu.main]]
    name = 'Services'
    pageRef = '/services'
    weight = 20
[[menu.main]]
    name = 'Features'
    pageRef = '/features'
    weight = 30
[[menu.main]]
    name = 'About'
    pageRef = '/about'
    weight = 40
[[menu.main]]
    name = 'Community'
    pageRef = '/community'
    weight = 50

[[menu.footer]]
    name = 'Legal'
    pageRef = '/legal'
    weight = 10
[[menu.footer]]
    name = 'Privacy'
    pageRef = '/privacy'
    weight = 20


[services]
    [services.googleAnalytics]
        ID = 'G-ZRGLRBL54N'